update to get errors and extract phpunit run to function

diff --git a/tcr b/tcr
--- a/tcr
+++ b/tcr
@@ -10,12 +10,23 @@ fi
 echo -e "\ntest && commit -a || restore .\n"
 
 app_dir=$(dirname $(dirname $(dirname $current_dir)))
-tmp_file=$app_dir/test_results.temp.txt
 phpunit=$app_dir/lib/pkp/lib/vendor/phpunit/phpunit/phpunit
 test_config=$app_dir/lib/pkp/tests/phpunit-env2.xml
 
-find . -name tests -type d -exec sh -c "php $phpunit --configuration $test_config -v \"{}\" | tee -a $tmp_file" \; && (grep -q "FAILURES\|ERRORS" $tmp_file && git restore . || git commit -a)
+run_phpunit() {
+    output=$(php $phpunit --configuration $test_config -v "$1")
+    echo "$output"
+    if (echo "$output" | grep -q "FAILURES!") || (echo "$output" | grep -q "ERRORS!"); then
+        return 1
+    else
+        return 0
+    fi
+}
 
-rm $tmp_file
+find . -name tests -type d | while read -r dir; do
+    run_phpunit "$dir"
+done
+
+[ $? -eq 1 ] && git restore . || git commit -a
 
 echo -e "\nEND OF TCR"
